import Config from "../constants/config";
import axios from "../lib/axios";

const postLogin = async (body) => {
  const { data } = await axios.post(`/login`, body);
  return data;
};

const getSidebar = async () => {
  const { data } = await axios.get(`/sidebar`);
  return data;
};

export const getGeneral = async () => {
  const { data } = await axios.get(`/mehr-panel`);
  return data;
};

const getCols = async (module) => {
  const { data } = await axios.get(`${module}`);
  return await data;
};

const getRows = async (module, props) => {
  const { data } = await axios.get(`${module}/data`, {
    params: {
      page: props.current,
      result: props.pageSize,
      filters: props.filters,
      search: props.search,
      locale: "all",
    },
  });
  return await data;
};

// const getRows = async (module, page, result, filters, search) => {
//   const { data } = await axios.get(`${module}/data`, {
//     params: {
//       page: page,
//       result: result,
//       filters,
//       search,
//       locale: "all",
//     },
//   });
//   return await data;
// };

export const getCreateOrEditFields = async (module, id = null) => {
  return [
    {
      type: "Group",
      originalName: "personal_details",
      name: "personal_details",
      valueType: "string",
      value: null,
      display: "Personal Details",
      placeholder: "",
      id: "personal_details",
      class: "personal_details",
      group: "all",
      col: 12,
      disable: false,
      readonly: false,
      showOnIndex: true,
      showOnDetail: true,
      showOnCreating: true,
      showOnEditing: true,
      sortable: true,
      searchable: false,
      rules: "",
      creationRules: "",
      updateRules: "",
      options: [],
      filter: [],
      filterable: false,
      multiple: false,
      comment: [],
      additional: false,
      subInputs: [{}, {}, {}, {}, {}, {}],
      children: [
        {
          type: "text",
          originalName: "first_name",
          name: "first_name",
          valueType: "string",
          value: null,
          display: "First Name",
          placeholder: "",
          id: "first_name",
          class: "first_name",
          group: "all",
          col: 16,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "last_name",
          name: "last_name",
          valueType: "string",
          value: null,
          display: "Last Name",
          placeholder: "",
          id: "last_name",
          class: "last_name",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "citizenship",
          name: "citizenship",
          valueType: "string",
          value: null,
          display: "Citizenship",
          placeholder: "",
          id: "citizenship",
          class: "citizenship",
          group: "all",
          col: 12,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "select",
          originalName: "gender",
          name: "gender",
          valueType: "string",
          value: null,
          display: "Gender",
          placeholder: "",
          id: "gender",
          class: "gender",
          group: "all",
          col: 6,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
          data: [
            {
              label: "Female",
              value: "female",
            },
            {
              label: "Man",
              value: "man",
            },
            {
              0: "trans",
              label: "Trans",
            },
          ],
        },
        {
          type: "text",
          originalName: "dob",
          name: "dob",
          valueType: "string",
          value: null,
          display: "Date Of Birth",
          placeholder: "",
          id: "dob",
          class: "dob",
          group: "all",
          col: 6,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "pob",
          name: "pob",
          valueType: "string",
          value: null,
          display: "Place Of Brith",
          placeholder: "",
          id: "pob",
          class: "pob",
          group: "all",
          col: 24,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
      ],
    },
    {
      type: "Group",
      originalName: "qualifications",
      name: "qualifications",
      valueType: "string",
      value: null,
      display: "Qualifications",
      placeholder: "",
      id: "qualifications",
      class: "qualifications",
      group: "all",
      col: 12,
      disable: false,
      readonly: false,
      showOnIndex: true,
      showOnDetail: true,
      showOnCreating: true,
      showOnEditing: true,
      sortable: true,
      searchable: false,
      rules: "",
      creationRules: "",
      updateRules: "",
      options: [],
      filter: [],
      filterable: false,
      multiple: false,
      comment: [],
      additional: false,
      subInputs: [{}, {}, {}, {}, {}, {}],
      children: [
        {
          type: "select",
          originalName: "job_area",
          name: "job_area",
          valueType: "string",
          value: null,
          display: "Job Area",
          placeholder: "",
          id: "job_area",
          class: "job_area",
          group: "all",
          col: 24,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
          data: [
            {
              label: "Elderly Care",
              value: "elderly_care",
            },
            {
              label: "Medicine",
              value: "Medicine",
            },
            {
              label: "nursing",
              value: "Nursing",
            },
            {
              label: "other",
              value: "Other",
            },
          ],
        },
        {
          type: "select",
          originalName: "job_position",
          name: "job_position",
          valueType: "string",
          value: null,
          display: "Job Position",
          placeholder: "",
          id: "job_position",
          class: "job_position",
          group: "all",
          col: 24,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "select",
          originalName: "speciality",
          name: "speciality",
          valueType: "string",
          value: null,
          display: "Speciality",
          placeholder: "",
          id: "speciality",
          class: "speciality",
          group: "all",
          col: 24,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "select",
          originalName: "german_proficiency",
          name: "german_proficiency",
          valueType: "string",
          value: null,
          display: "German Proficiency",
          placeholder: "",
          id: "german_proficiency",
          class: "german_proficiency",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
          data: [],
        },
        {
          type: "select",
          originalName: "current_course",
          name: "current_course",
          valueType: "string",
          value: null,
          display: "Current Course",
          placeholder: "",
          id: "current_course",
          class: "current_course",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "select",
          originalName: "current_course_chapter",
          name: "current_course_chapter",
          valueType: "string",
          value: null,
          display: "Current Course Chapter",
          placeholder: "",
          id: "current_course_chapter",
          class: "current_course_chapter",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
      ],
    },
    {
      type: "Group",
      originalName: "contact_details",
      name: "contact_details",
      valueType: "string",
      value: null,
      display: "Contact Details",
      placeholder: "",
      id: "contact_details",
      class: "contact_details",
      group: "all",
      col: 12,
      disable: false,
      readonly: false,
      showOnIndex: true,
      showOnDetail: true,
      showOnCreating: true,
      showOnEditing: true,
      sortable: true,
      searchable: false,
      rules: "",
      creationRules: "",
      updateRules: "",
      options: [],
      filter: [],
      filterable: false,
      multiple: false,
      comment: [],
      additional: false,
      subInputs: [{}, {}],
      children: [
        {
          type: "text",
          originalName: "email",
          name: "email",
          valueType: "string",
          value: null,
          display: "Email",
          placeholder: "",
          id: "email",
          class: "email",
          group: "all",
          col: 12,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "phone",
          name: "phone",
          valueType: "string",
          value: null,
          display: "Phone",
          placeholder: "",
          id: "phone",
          class: "phone",
          group: "all",
          col: 12,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
      ],
    },
    {
      type: "Group",
      originalName: "preferences",
      name: "preferences",
      valueType: "string",
      value: null,
      display: "Preferences",
      placeholder: "",
      id: "preferences",
      class: "preferences",
      group: "all",
      col: 12,
      disable: false,
      readonly: false,
      showOnIndex: true,
      showOnDetail: true,
      showOnCreating: true,
      showOnEditing: true,
      sortable: true,
      searchable: false,
      rules: "",
      creationRules: "",
      updateRules: "",
      options: [],
      filter: [],
      filterable: false,
      multiple: false,
      comment: [],
      additional: false,
      subInputs: [{}, {}, {}],
      children: [
        {
          type: "text",
          originalName: "preferred_cities",
          name: "preferred_cities",
          valueType: "string",
          value: null,
          display: "Preferred Cities",
          placeholder: "",
          id: "preferred_cities",
          class: "preferred_cities",
          group: "all",
          col: 18,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "available_from",
          name: "available_from",
          valueType: "string",
          value: null,
          display: "Available From",
          placeholder: "",
          id: "available_from",
          class: "available_from",
          group: "all",
          col: 6,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "select",
          originalName: "preferred_facility_types",
          name: "preferred_facility_types",
          valueType: "string",
          value: null,
          display: "Preferred Facility Types",
          placeholder: "",
          id: "preferred_facility_types",
          class: "preferred_facility_types",
          group: "all",
          col: 24,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
          data: [
            {
              label: "Hospitals/Clinics",
              value: "hospital_clinics",
            },
            {
              label: "Ambulance Service",
              value: "ambulance_service",
            },
          ],
        },
      ],
    },
    {
      type: "Group",
      originalName: "address",
      name: "address.1",
      valueType: "string",
      value: null,
      display: "Address",
      placeholder: "",
      id: "address",
      class: "address",
      group: "all",
      col: 12,
      disable: false,
      readonly: false,
      showOnIndex: true,
      showOnDetail: true,
      showOnCreating: true,
      showOnEditing: true,
      sortable: true,
      searchable: false,
      rules: "",
      creationRules: "",
      updateRules: "",
      options: [],
      filter: [],
      filterable: false,
      multiple: false,
      comment: [],
      additional: true,
      subInputs: [{}, {}, {}, {}, {}],
      children: [
        {
          type: "text",
          originalName: "street",
          name: "address.1.street",
          valueType: "string",
          value: null,
          display: "Street",
          placeholder: "",
          id: "street",
          class: "street",
          group: "all",
          col: 18,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "number",
          name: "address.1.number",
          valueType: "string",
          value: null,
          display: "Number",
          placeholder: "",
          id: "number",
          class: "number",
          group: "all",
          col: 6,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "zip",
          name: "address.1.zip",
          valueType: "string",
          value: null,
          display: "Zip",
          placeholder: "",
          id: "zip",
          class: "zip",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "city",
          name: "address.1.city",
          valueType: "string",
          value: null,
          display: "City",
          placeholder: "",
          id: "city",
          class: "city",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
        {
          type: "text",
          originalName: "country",
          name: "address.1.country",
          valueType: "string",
          value: null,
          display: "Country",
          placeholder: "",
          id: "country",
          class: "country",
          group: "all",
          col: 8,
          disable: false,
          readonly: false,
          showOnIndex: true,
          showOnDetail: true,
          showOnCreating: true,
          showOnEditing: true,
          sortable: true,
          searchable: false,
          rules: "",
          creationRules: "",
          updateRules: "",
          options: [],
          filter: [],
          filterable: false,
          multiple: false,
          comment: [],
          additional: false,
        },
      ],
    },
  ];

  if (id) {
    const { data } = await axios.get(`${module}/${id}/edit?locale=all`);
    return await data;
  } else {
    const { data } = await axios.get(`${module}/create`);
    return await data;
  }
};

export const postCreate = async (module, body) => {
  const { data } = await axios.post(`${module}`, body);
  return await data;
};

export const postEdit = async (module, id, body) => {
  const { data } = await axios.put(`${module}/${id}`, body);
  return await data;
};

export const postEditOrCreate = async (module, id, body) => {
  if (id) {
    const { data } = await axios.put(`${module}/${id}`, body);
    return await data;
  } else {
    const { data } = await axios.post(`${module}`, body);
    return await data;
  }
};

const getSelect = async (dataUrl, q) => {
  const { data } = await axios.get(`${dataUrl}&locale=all&search=${q}`);
  return await data;
};

const getSelectValue = async (dataUrl, id) => {
  const { data } = await axios.get(dataUrl, {
    params: {
      id: id,
    },
  });
  return await data;
};

const deleteRow = async (module, id) => {
  const { data } = await axios.delete(`${module}/${id}?locale=all`);
  return await data;
};

const uploadImage = async (file) => {
  const formData = new FormData();
  formData.append("file", file);

  console.log("🚀 ~ file: index.js ~ line 72 ~ uploadImage ~ file", file);
  const { data } = await axios.post(`/file-manager/upload`, formData);

  return await data;
};

export {
  postLogin,
  getSidebar,
  getCols,
  getRows,
  // postCreate,
  // postEditOrCreate,
  getSelect,
  getSelectValue,
  deleteRow,
  uploadImage,
};
